include:
- ./func/*
kind: ArchiveUploadSpec
name: func-jAx0

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: get-ticket-details-fn-a26cde83-9c19-4664-9a15-a24bc31f702a
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: get-ticket-details-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-jAx0
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-07-12T14:08:45Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: get-ticket-details-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 1
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 80
    StrategyType: execution
  concurrency: 500
  environment:
    name: get-ticket-details-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.get_user_ticket_details
    packageref:
      name: get-ticket-details-fn-a26cde83-9c19-4664-9a15-a24bc31f702a
      namespace: default
  requestsPerPod: 1
  resources: {}
