apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: get-ticket-details-rt
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: get-ticket-details-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /support/get-ticket-details
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /support/get-ticket-details
