include:
- ./func/*
kind: ArchiveUploadSpec
name: func-wEuK

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: get-user-ticket-details-fn-135aab8c-9634-4399-b1dd-05bf5d11410d
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: get-user-ticket-details-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-wEuK
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-01-31T20:12:42Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: get-user-ticket-details-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: get-user-ticket-details-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.fn
    packageref:
      name: get-user-ticket-details-fn-135aab8c-9634-4399-b1dd-05bf5d11410d
      namespace: default
  requestsPerPod: 1
  resources: {}
