include:
- ./func/*
kind: ArchiveUploadSpec
name: func-EfMO

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: get-user-ticket-details-fn-4af2c5cb-e7ba-4c40-b3a1-f1ef2655b8c1
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: get-user-ticket-details-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-EfMO
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-03-04T16:35:37Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: get-user-ticket-details-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: get-user-ticket-details-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.fn
    packageref:
      name: get-user-ticket-details-fn-4af2c5cb-e7ba-4c40-b3a1-f1ef2655b8c1
      namespace: default
  requestsPerPod: 1
  resources: {}
