apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: aa250d48-16d0-4643-9920-f83d6f2b4ec7
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: get-user-ticket-details-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /get_user_ticket_details
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /get_user_ticket_details
